name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Expo CLI
        run: npm install -g expo-cli

      - name: Install dependencies
        run: npm install

      - name: Build APK
        run: expo build:android -t apk
